name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    steps:
      - run: npm run build
      - run: cd build
